export * from "./RegisterTemplates"
export * from "./LoginTemplate"
export * from "./HomeTemplate"
export * from "./MovieBookingTemplate"
export * from "./MovieDetailTemplate"
export * from "./ShowTimesTemplate"
export * from "./Account"